function doit(){
    const HEADER_PY = "import numpy as np\n\
from copy import deepcopy\n\
from queue import PriorityQueue # put, get, qsize\n\
from collections import deque # append(left), pop(left), extend";

    function log(a){
        console.log("leetcode-extention: ",a)
    }

    function checkHeader(code, lang){    // check if the code needs to add header.
        if(lang==="python3"){
            return code.substr(0, 5)!=="#####";
        }
        return false;
    }

    setTimeout(()=>{
        monaco.editor.onDidChangeModelLanguage((e)=>{
            setTimeout(()=>{
                let m = e.model;
                let lang = m._languageIdentifier.language;

                monaco.languages.setLanguageConfiguration(lang,{autoClosingPairs:[],surroundingPairs:[]});
                log("Set autoBracketing=False for "+lang);
                
                if(lang==="python3"){
                    let now = m.getValue();
                    if(checkHeader(now, lang))
                        m.setValue('##### Generated by Leetcode-extension by Littledva\n\n'+HEADER_PY+'\n\n##### Solution \n'+now);
                }
            }, 400);
        });
    }, 2400);
}

$(()=>{
    scriptContent = doit.toString() + ';doit();';
    var script = document.createElement('script');
    script.id = 'leetcode-extention-js';
    script.appendChild(document.createTextNode(scriptContent));
    document.body.appendChild(script);
});